services:
  lemanchot_analysis:
    image: lemanchotanalysis:latest
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 12G
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: 1
    volumes:
      - /data:/data
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
