
@startuml

!theme plain

title LeManchot VT-Smart Process Pipeline

group Multi-Modal Imagery Data

split
   -[hidden]->
   :Visible Image Stream;
split again
   -[hidden]->
   :Thermal Image Stream;
end split

end group

:Preprocess the images;
:Thermal-Visible Modalities Registration;
split
  :Apply Segmentation on Visible Images;
split again
  :Apply Segmentation on Thermal Images;
end split

:Use the visible image segmentation to enhance images;

stop

@enduml